using System.Collections.Generic;

using Newtonsoft.Json;

namespace Tsukumo.OpenAI.Models.ChatCompletion.Messages
{
    public class AssistantMessage : Message
    {
        public AssistantMessage(string content) : base(content, Roles.Assistant, null) { }

        /// <summary>
        /// The tool calls generated by the model, such as function calls.
        /// </summary>
        /// <value>Optional.</value>
        [JsonProperty("tool_calls", NullValueHandling = NullValueHandling.Ignore)]
        public List<ToolCall> ToolCalls { get; set; }
    }
}
