using System.Collections.Generic;

using Newtonsoft.Json;

namespace Tsukumo.OpenAI.Models.ChatCompletion
{
    public class ChoiceMessage
    {
        /// <summary>
        /// The role of the author of this message.
        /// </summary>
        [JsonProperty("role")]
        public string Role { get; set; }

        /// <summary>
        /// The contents of the message.
        /// </summary>
        [JsonProperty("content")]
        public string Content { get; set; }

        /// <summary>
        /// Reasoning text split out from <see cref="Content"/> by the server.
        /// Deserialized from <c>reasoning_content</c> (e.g. vLLM, LM Studio), <c>reasoning</c> (e.g. xAI, Groq), or <c>thinking</c> (e.g. Ollama), whichever is present.
        /// </summary>
        [JsonIgnore]
        public string Reasoning
        {
            get => _reasoning ?? _reasoningContent ?? _thinking;
            set
            {
                _reasoning = value;
                _reasoningContent = _thinking = null;
            }
        }

        /// <summary>
        /// The tool calls generated by the model, such as function calls.
        /// </summary>
        [JsonProperty("tool_calls")]
        public List<ToolCall> ToolCalls { get; set; }

        [JsonProperty("reasoning_content")]
        private string _reasoningContent;

        [JsonProperty("reasoning")]
        private string _reasoning;

        [JsonProperty("thinking")]
        private string _thinking;
    }
}
