using Newtonsoft.Json;

namespace Tsukumo.OpenAI.Models.ChatCompletion
{
    /// <summary>
    /// The tool calls generated by the model, such as function calls.
    /// </summary>
    public class ToolCall
    {
        /// <summary>
        /// The ID of the tool call.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// The type of the tool. Currently, only function is supported.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }

        /// <summary>
        /// The function that the model called.
        /// </summary>
        [JsonProperty("function")]
        public ToolCallsFunction Function { get; set; }
    }
}
